theme: jekyll-theme-slate
url: "https://sykefi.github.io/kaavamaaraysoppaat" # the base hostname & protocol for your site
home: "https://sykefi.github.io/kaavamaaraysoppaat/"
name: "Kaavamääräysoppaat"
name_short: "Kaavamääräysoppaat"
repository: sykefi/kaavamaaraysoppaat
beta: true
#google_analytics: G-TL17CQFMFK
plugins:
- jekyll-sitemap
- kramdown


